add upload photo
BondarKY/simple-instagram pull request #3
Opened 2020-10-17 16:38 UTC by BondarKY

2020-10-17 17:57 UTC, FOXHOUNDEX requested changes

2020-10-17 17:57 UTC, FOXHOUNDEX commented on src/components/Header/HeaderContainer.js
> +        const token = this.props.access_token;
переделай через async await

2020-10-18 18:29 UTC, vitaliikotliar commented on src/components/Gallery/GalleryContainer.js
>  const mapStateToProps = state => {
For small reducers could be simplified to:
```
const mapStateToProps = data => data.userReducer
```

2020-10-18 18:29 UTC, vitaliikotliar commented on src/components/Gallery/GalleryContainer.js
>  export default connect(mapStateToProps, mapDispatchToProps)(GalleryContainer);
At the end of this line you are probably seeing "No newline at the end of file" warning.

It's just a common practice to insert newline at the end of any file, otherwise it may cause unexpected issues. See [this comment](https://stackoverflow.com/a/729795/6282146)

2020-10-18 18:29 UTC, vitaliikotliar commented on src/components/Header/Header.css
> +.header .nav-btns {
Pay your attention to [SASS](https://sass-lang.com/), it's super useful!

2020-10-18 18:29 UTC, vitaliikotliar commented on src/components/Header/Header.js
> +                        <svg height="22" viewBox="0 0 48 48" width="22"><path d="M45.3 48H30c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2-4.6-4.6-4.6s-4.6 2-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5
SVG graphics could be extracted to separate component, like `LoginIcon`.

2020-10-20 08:42 UTC, BondarKY commented on src/components/Header/Header.css
> +.header .nav-btns {
Thanks. I will start using

2020-10-20 08:53 UTC, FOXHOUNDEX approved these changes

2020-10-26 12:45 UTC, vitaliikotliar approved these changes

2020-10-26 12:45 UTC, vitaliikotliar commented on src/components/icons/FeedIcon.js
> +    const { height = '22', width = '22' } = props;
Props like these may be omitted if the component will not be changed)

2020-10-27 09:09 UTC, merged